# Generated by Django 4.2 on 2025-04-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='game_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Message texte'), ('game_invite', 'Invitation à jouer')], default='text', max_length=20),
        ),
    ]
