# Generated by Django 4.2 on 2025-03-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
