# Generated by Django 4.2 on 2025-04-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
