# Generated by Django 4.2 on 2025-03-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_utilisateurs_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
