# Generated by Django 4.2 on 2025-03-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_utilisateurs_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
