# Generated by Django 4.2 on 2025-03-16 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
