##################################################################################
### Nous utilisons l'image officielle PostgreSQL et définissons les variables  ###
### d'environnement pour la création de la base de données et de l'utilisateur.###
### Le port 5432 est exposé pour permettre les connexions à la base de données.###
##################################################################################

FROM postgres:14-alpine

EXPOSE 5432
