# Generated by Django 4.2 on 2025-03-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_player1_is_playing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1_is_playing',
        ),
    ]
