# Generated by Django 4.2 on 2025-04-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_morpionmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='morpionmatch',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='morpionmatch',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
