# Generated by Django 4.2 on 2025-04-03 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_morpionmatch_player1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morpionmatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_morpion_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
