# Generated by Django 4.2 on 2025-04-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_morpionmatch_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morpionmatch',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
