# Generated by Django 4.2 on 2025-04-01 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du tournoi')),
                ('statut', models.CharField(choices=[('en_attente', 'Attente'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournois_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('gagnant_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournois_gagnes', to=settings.AUTH_USER_MODEL, verbose_name='Gagnant du tournoi')),
                ('joueurs', models.ManyToManyField(blank=True, related_name='tournois', to=settings.AUTH_USER_MODEL, verbose_name='Joueurs')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_joueur1', models.IntegerField(default=0, verbose_name='Score Joueur 1')),
                ('score_joueur2', models.IntegerField(default=0, verbose_name='Score Joueur 2')),
                ('round', models.CharField(choices=[('demi_finale', 'Demi-finale'), ('finale', 'Finale')], default='demi_finale', max_length=20, verbose_name='Phase du match')),
                ('date_match', models.DateTimeField(auto_now_add=True, verbose_name='Date du match')),
                ('gagnant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matchs_gagnes', to=settings.AUTH_USER_MODEL, verbose_name='Gagnant')),
                ('joueur1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_joueur1', to=settings.AUTH_USER_MODEL, verbose_name='Joueur 1')),
                ('joueur2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_joueur2', to=settings.AUTH_USER_MODEL, verbose_name='Joueur 2')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs', to='tournois.tournoi', verbose_name='Tournoi')),
            ],
        ),
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Joueur')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='tournois.tournoi', verbose_name='Tournoi')),
            ],
        ),
    ]
