# Generated by Django 4.2 on 2025-04-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='joueurs_noms_personnalises',
            field=models.JSONField(blank=True, default=dict, verbose_name='Noms personnalisés des joueurs'),
        ),
    ]
