# Generated by Django 4.2 on 2025-04-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0002_tournoi_joueurs_noms_personnalises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['ordre']},
        ),
        migrations.AddField(
            model_name='match',
            name='ordre',
            field=models.IntegerField(default=0, verbose_name='Ordre du match'),
        ),
    ]
