# Generated by Django 4.2 on 2025-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournois', '0004_match_joueur1_nom_match_joueur2_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gagnant_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom personnalisé du gagnant'),
        ),
    ]
